### ISSUE TITLE
Our partners - BS chart scaling

### ISSUE THREAD

**Issue by melish** [eftafmo/dataviz#520]
Open https://data.eeagrants.org/partners/?beneficiary=CY#results
using a width: 900px

(open pre-filtered link directly)
=> bars for Norway are not properly scaled

**Comment by melish** [comment]
![screen shot 2017-10-30 at 12 18 24](https://user-images.githubusercontent.com/1218168/32165759-89d0cc0c-bd6c-11e7-81f0-8324139f7e4b.png)

**Comment by xlotlu** [comment]
problem is caused by the sidebar (i.e., the `<aside>`) causing the content container to reflow.

the content should be fixed-width from the start.
